### PR TITLE
F/A-18C: Fix eight magnetically-held switches with deferred-release pattern

### LINKED ISSUE #1624: F/A-18C: Eight magnetically-held switches broken (Detailed bug report)
I've been building physical F/A-18C cockpit panels with ESP32 boards and DCS-BIOS, and I ran into the well-known APU switch issue. After investigating, I found that the problem is wider than just the APU and affects **all eight magnetically-held switches** in the Hornet. I'd love to get your thoughts on a proposed fix.

## The bug

F/A-18C magnetically-held switches are `class_type.BTN` widgets with `use_release_message = true`. The C++ device handler expects two `performClickableAction` calls on the same command ID — value `1` (press) and value `0` (release) — arriving in **separate frames**. This is how every input path in DCS operates these switches:

- **Mouse:** press on mouse-down, release on mouse-up
- **Keyboard:** ED's own bindings use `value_down = 1.0` / `value_up = 0.0`
- **A-10C:** `defineElectricallyHeldSwitch` correctly sends separate press/release commands

DCS-BIOS for the F/A-18C does not send the required press-then-release sequence. If only the press arrives without the release, the switch actuates but is left in an inconsistent state — the magnetic latch sequence never completes, so the system doesn't settle into the correct selenoid armed/disarmed condition.

## Affected switches

All eight were assigned one of four existing functions, and each function fails differently:

| Switch | Current Function | Sends Release? | Problem |
|--------|-----------------|----------------|---------|
| `LAUNCH_BAR_SW` | `defineToggleSwitchToggleOnly` | Never | Always sends value 1, never 0 |
| `HOOK_BYPASS_SW` | `defineToggleSwitchToggleOnly` | Never | Always sends value 1, never 0 |
| `FUEL_DUMP_SW` | `defineToggleSwitchToggleOnly` | Never | Always sends value 1, never 0 |
| `APU_CONTROL_SW` | `defineToggleSwitchToggleOnly` | Never | Always sends value 1, never 0 |
| `ENGINE_CRANK_SW` | `defineRockerSwitch` | Yes | No frame separation guarantee |
| `PITOT_HEAT_SW` | `defineToggleSwitchToggleOnly` | Never | Always sends value 1, never 0 |
| `LTD_R_SW` | `defineToggleSwitch` | As position | Treats BTN as TUMB (wrong semantics) |
| `CANOPY_SW` | `defineRockerSwitch` | Yes | OPEN direction is magnetic — no frame separation guarantee |

**`defineToggleSwitchToggleOnly`** (5 switches) — always sends `performClickableAction(cmd, 1)` regardless of direction. Never sends value 0. The release never arrives.

**`defineToggleSwitch`** (LTD/R) — maps input directly to command value: `"1"` sends value 1, `"0"` sends value 0. Treats press/release as absolute positions like a TUMB switch. But this is a BTN — both arming AND disarming require press(1) then release(0). Sending value 0 alone is a release without a preceding press.

**`defineRockerSwitch`** (Engine Crank, Canopy) — sends correct values but on separate user actions with no timing guarantee. Works with physical hardware (natural human delay between actions) but fails for programmatic inputs (BORT, direct UDP) where press and release can arrive in the same frame. Also has a known float comparison bug (`fromState == 1` fails when arg returns `0.999`).

The Canopy is an **asymmetric** case: only the OPEN direction is magnetically held (solenoid engages, canopy opens fully, switch auto-releases). The CLOSE direction is a manual hold — you hold the switch down and the canopy motor runs. The DCS auto-start macro confirms this: OPEN sends press→release immediately (`dt` apart), while CLOSE holds for 8 full seconds before releasing.

## Related issues

This has been reported multiple times over the past 3+ years:

- #55 — APU switch not working with external hardware
- #134 — Duplicate APU switch report
- #144 — APU fix discussion (Feb 2023): `defineToggleSwitch` was applied by @WarLord211 in commit `3098662`, then reverted 5 hours later in `16c5061` due to state desync concerns
- #855 — Recent magnetic switch report

The revert in #144 was warranted — `defineToggleSwitch` has the wrong semantics for BTN-class switches (it treats them as TUMB). The fix we're proposing takes a different approach.

## Proposed fix

Two new functions added to `FA-18C_hornet.lua` (not Module.lua) that implement a **deferred-release pattern**: fire the press immediately, then count down in the export hook (which already runs every frame at ~30Hz), and fire the release after 3 frames (~100ms). This guarantees frame separation without timers, coroutines, or threads.

- **`defineElectricallyHeldSwitch`** — 2-position (6 call sites: APU, Launch Bar, Hook Bypass, Fuel Dump, Pitot Heat, LTD/R)
- **`defineElectricallyHeld3PosTumb`** — 3-position (2 call sites: Engine Crank, Canopy)

The 3-position function supports an optional `magnetic_direction` attribute for asymmetric switches like the Canopy — where only one direction needs deferred release. Default is `"both"` (Engine Crank), `"pos"` means only the positive direction is magnetic (Canopy OPEN), while the other direction behaves as a normal rocker.

Edge cases handled:
- **Rapid double-press:** pending release fires immediately before new press (flush-before-press)
- **Mission end while release pending:** export loop stops, pending release never fires — harmless, DCS resets all state
- **Direction change on 3-pos:** pending release flushes before engaging new direction
- **Float comparison:** uses `Module.round()` to fix the known `fromState == 1` bug in `defineRockerSwitch` (Module.lua:905)

## Scope of changes

**One file touched. Two functions added. Eight one-line call-site swaps. That's it.**

```
File:      lib/modules/aircraft_modules/FA-18C_hornet.lua
Added:     defineElectricallyHeldSwitch (2-pos)
           defineElectricallyHeld3PosTumb (3-pos, with magnetic_direction param)
Changed:   8 call sites (function name swap, identical or reduced parameters)
```

What is NOT changed:
- **Module.lua** — untouched, no framework modifications
- **Other aircraft modules** — untouched
- **Arduino library / firmware** — zero changes, every existing hardware setup benefits automatically
- **Memory map addresses** — unchanged, same `allocateInt` bit widths
- **New imports** — none, the functions use only what `FA-18C_hornet.lua` already imports

## CI verification

We cloned the repo, applied the changes, and ran the exact CI pipeline locally:

| CI Check | Result |
|----------|--------|
| `luacheck` | 0 warnings, 0 errors |
| `StyLua v2.1.0` | Fully compliant |
| `LocalCompile.lua` | All 47 modules compile |
| `TestSuite.lua` | **286/286 tests passed, 0 failures** |
| `verify-addresses` (Addresses.h diff) | **Zero diff** — memory map identical to upstream |

## Community testing

We've been running this fix on our own hardware (ESP32 cockpit panels, multiple switch types) and community members in the [OpenHornet](https://openhornet.com) Discord tested it on their builds and reported successful operation of the magnetic switches.

## How we'd like to proceed

We're happy to submit a PR with the complete changes, or if you'd prefer, we can provide the diff and a maintainer can commit it directly. The changes are small enough to review in minutes — two function definitions and eight one-line swaps in a single file.

We put together a detailed technical document covering the full root cause analysis, the DCS widget architecture, the A-10C comparison, the proposed functions with inline comments, backward compatibility analysis, and CI results. It's available here if you'd like the full picture:

**[TN-2026-003-R4 — Full Technical Analysis](https://www.bojote.com/dcsbios/v4/)**

A unified diff patch file is also available for easy testing against a vanilla install:

**[magnetic-switches.patch](https://www.bojote.com/dcsbios/v4/magnetic-switches.patch)** — applies with `patch -p1` from the DCS-BIOS root. Includes both function definitions and all eight call-site swaps.

Would love to hear your thoughts. Thanks for maintaining this project — it's what makes builds like ours possible.

### PR DESCRIPTION
**Pull request by BojoteX**
Fixes #1624

## Summary

- Adds two new functions to `FA-18C_hornet.lua` that correctly handle magnetically-held (electrically-held) switches by sending press (value 1) then release (value 0) in separate frames
- Replaces eight broken call sites with the new functions -- same control identifiers, same memory map, zero firmware changes required
- Follows the same pattern already established by the A-10C module defineElectricallyHeldSwitch

## The problem

F/A-18C magnetically-held switches are `class_type.BTN` widgets where both press and release share the **same command ID**. The C++ device handler expects value 1 (press) and value 0 (release) to arrive in separate frames to complete the magnetic latch sequence.

The current definitions do not send the release:
- 5 use `defineToggleSwitchToggleOnly` -- sends value 1, never sends value 0
- 1 uses `defineToggleSwitch` -- sends value 0 directly (wrong semantics for BTN, release without press)
- 2 use `defineRockerSwitch` -- no frame separation guarantee, plus float comparison bug

This has been reported in #55, #134, #144, and #855 over the past 3+ years. A previous fix attempt in #144 used `defineToggleSwitch`, which was correctly reverted because it has the wrong semantics for BTN-class widgets. This PR takes a fundamentally different approach: instead of treating the switch as a TUMB with absolute positions, it sends the correct press-then-release sequence that BTN-class widgets require.

## ED keyboard bindings confirm press+release

Every one of these 8 switches is defined in `Input/FA-18C/keyboard/default.lua` with `value_down = 1.0, value_up = 0.0`:

| Switch | Keyboard Binding | value_down | value_up |
|--------|-----------------|------------|----------|
| APU | `engines_commands.APU_ControlSw` | 1.0 | 0.0 |
| Launch Bar | `gear_commands.LaunchBarSw` | 1.0 | 0.0 |
| Hook Bypass | `cptlights_commands.HookBypass` | 1.0 | 0.0 |
| Fuel Dump | `fuel_commands.DumpSw` | 1.0 | 0.0 |
| Pitot Heat | `elec_commands.PitotHeater` | 1.0 | 0.0 |
| LTD/R | `tgp_commands.LtdrArm_ITER` | 1.0 | 0.0 |
| Canopy OPEN | `cpt_commands.CanopySwitchOpen` | 1.0 | 0.0 |
| Engine Crank L | `engines_commands.EngineCrankLSw` | -1.0 | 0.0 |
| Engine Crank R | `engines_commands.EngineCrankRSw` | 1.0 | 0.0 |

This is ED's own input contract for these switches: press on key-down, release on key-up. The deferred release in this PR replicates exactly what ED designed. We are not inventing behavior -- we are matching it.

The widget definitions in `clickable_defs.lua` confirm this further: these widgets use `class = {class_type.BTN}` with `use_release_message = {true, true}` and a `stop_action` that fires on mouse-up. ED explicitly designed these switches to receive both press and release.

## The fix

Two functions added to `FA-18C_hornet.lua` (not Module.lua):

**`defineElectricallyHeldSwitch`** (2-position, 6 call sites)
Fire `performClickableAction(command, 1)` immediately, then use the existing export hook (already runs every frame at ~30Hz) to count down 3 frames and fire `performClickableAction(command, 0)`. No timers, no coroutines -- just a `release_countdown` upvalue closed over by the export hook.

**`defineElectricallyHeld3PosTumb`** (3-position, 2 call sites)
Same pattern, but tracks which direction command needs releasing. Supports an optional `magnetic_direction` attribute for asymmetric switches: `"both"` (Engine Crank, default), `"pos"` (Canopy -- OPEN is magnetic, CLOSE is manual hold).

Edge cases:
- **Rapid double-press:** pending release flushes immediately before new press
- **3-pos direction change:** pending release flushes before engaging new direction
- **Center return:** releases fire immediately (spring-return, no solenoid involvement)

## A-10C precedent

The A-10C already handles this class of switch with its own `defineElectricallyHeldSwitch` (A-10C.lua, line 129). The A-10C version sends press AND release in the **same frame** -- even more aggressive than our 3-frame deferral -- because the A-10C has two separate command IDs per switch (pos_command / neg_command).

The F/A-18C cannot do that -- press and release share one command ID, and DCS drops one when both arrive in the same frame. The 3-frame deferral is the minimum change needed to work within the Hornet single-command architecture.

Key point: **the A-10C also sends an automatic release when it receives a "1" input.** When DCS-BIOS receives `LASTE_EAC 1`, it fires both `performClickableAction(3026, 1)` and `performClickableAction(3027, 0)` immediately. There is no hold behavior in the A-10C either. This has been shipping without issues.

## What about holding the switch?

Magnetic switches in the real aircraft are momentary actions -- you press, the solenoid either latches or it does not, and the switch spring-returns. They are not designed to be held. The DCS cockpit widgets reflect this: they are `class_type.BTN` (momentary), not `class_type.TUMB` (latching).

DCS-BIOS operates on discrete commands over UDP. A command arrives, it is processed, it is done. There is no continuous held state in the protocol. This is fundamentally different from mouse input (where button-down persists until button-up) or HID joystick input (where a latching toggle keeps reporting button-held).

Since DCS-BIOS cannot express a held state, the only options are:
1. Send press only, never release (current behavior -- **broken**)
2. Send press and release in the same frame (what A-10C does -- works because two command IDs)
3. Send press, defer release by N frames (what this PR does -- required because one command ID)

Option 3 is the only one available for the F/A-18C single-command architecture, and it matches the A-10C intent: on command receipt, complete the full press+release cycle automatically.

For users with regular (non-magnetic) toggle switches on their panels: this fix makes the sim switch behave correctly. The physical toggle stays latched in position (because that is what physical toggles do), and the sim switch engages/disengages properly. The only theoretical side effect is that if the solenoid does not latch (e.g., no electrical power), the sim switch will fall back after 3 frames while the physical toggle stays up. But this is the same behavior the A-10C has always had, and it reflects reality -- you cannot force an unpowered magnetic switch to stay engaged by holding it.

## Why fix the existing controls instead of adding new ones?

These 8 switches are special-purpose magnetic switches, not general-purpose controls. They have a specific physical behavior (press-and-release) that the current definitions fail to implement. The existing control identifiers, memory addresses, and firmware integrations are all correct -- the only thing wrong is the command sequence sent to DCS.

Adding new controls alongside the broken ones would mean:
- Every builder has to update their firmware to use the new control names
- The old broken controls remain in the codebase indefinitely, confusing new users
- The memory map grows with duplicate entries for the same physical switches
- Non-Arduino consumers (custom UDP clients, BORT, other tools) all need updating too

Fixing in place means every existing setup -- ESP32 boards, Arduino builds, custom UDP clients, BORT -- works correctly the moment DCS-BIOS is updated. Zero firmware changes. Zero configuration changes. The control names and addresses stay the same because they ARE the right controls, they just needed the right command sequence.

The issue is not the control label or identifier -- it is the semantics of how the command is sent. A magnetic switch labeled `APU_CONTROL_SW` should still be called `APU_CONTROL_SW`. The name is correct. The address is correct. What was wrong was that it was sending only half the message DCS expects.

## Why fix this in Lua, not in firmware?

The constraint is **aircraft-specific**, not hardware-specific. The F/A-18C uses single-command magnetic switches; the A-10C uses dual-command switches. Firmware should not need per-aircraft workarounds -- that is the entire purpose of per-aircraft Lua modules.

A Lua fix benefits every DCS-BIOS consumer automatically. A firmware fix would require every builder to reflash every board and would not help non-Arduino clients at all.

## Affected switches

| Switch | Was | Now | Notes |
|--------|-----|-----|-------|
| `APU_CONTROL_SW` | `defineToggleSwitchToggleOnly` | `defineElectricallyHeldSwitch` | |
| `LAUNCH_BAR_SW` | `defineToggleSwitchToggleOnly` | `defineElectricallyHeldSwitch` | |
| `HOOK_BYPASS_SW` | `defineToggleSwitchToggleOnly` | `defineElectricallyHeldSwitch` | |
| `FUEL_DUMP_SW` | `defineToggleSwitchToggleOnly` | `defineElectricallyHeldSwitch` | |
| `PITOT_HEAT_SW` | `defineToggleSwitchToggleOnly` | `defineElectricallyHeldSwitch` | |
| `LTD_R_SW` | `defineToggleSwitch` | `defineElectricallyHeldSwitch` | |
| `ENGINE_CRANK_SW` | `defineRockerSwitch` | `defineElectricallyHeld3PosTumb` | |
| `CANOPY_SW` | `defineRockerSwitch` | `defineElectricallyHeld3PosTumb` | `magnetic_direction = "pos"` |

## What is NOT changed

- **Module.lua** -- untouched
- **Other aircraft modules** -- untouched
- **Control identifiers** -- identical (same names, same memory addresses)
- **Arduino library / firmware** -- zero changes, every existing setup benefits automatically
- **Memory map** -- `verify-addresses` confirms zero diff against upstream Addresses.h

## Note on Module.round()

The new functions call `Module.round()` on `get_argument_value()` results internally. This is not a fix to existing code -- it is how the new functions are written to avoid the known float imprecision issue (where DCS returns 0.999 instead of 1.0). No existing functions or Module.lua are modified.

## CI verification

| Check | Result |
|-------|--------|
| luacheck | 0 warnings, 0 errors |
| StyLua v2.1.0 | Fully compliant |
| LocalCompile.lua | All 47 modules compile |
| TestSuite.lua | 286/286 tests passed, 0 failures |
| verify-addresses | Zero diff -- memory map identical to upstream |

## Test plan

- [ ] Cold start with APU -- verify APU engages and stays running
- [ ] Engine Crank LEFT/RIGHT -- verify starter engages, crank completes
- [ ] LTD/R ARM/SAFE -- verify laser tracker arms/disarms
- [ ] Launch Bar extend/retract
- [ ] Hook Bypass FIELD/CARRIER
- [ ] Fuel Dump ON/OFF (airborne with fuel)
- [ ] Pitot Heat ON/AUTO
- [ ] Canopy OPEN (magnetic) and CLOSE (manual hold, 8 seconds)
- [ ] Rapid toggle -- flip switch back and forth quickly, verify no stuck state
- [ ] BORT programmatic test -- send commands via UDP, verify same behavior
- [ ] Verify all 8 switches with physical hardware (ESP32 toggle panels)

## References

- GitHub Issue: #1624
- [Technical Document (TN-2026-003-R4)](https://www.bojote.com/dcsbios/v4/)
- [Patch file](https://www.bojote.com/dcsbios/v4/magnetic-switches.patch)

### CODE REVIEW

**Comment by kbastronomics** [comment]
Thanks for all your hard work on this, this has been tested by open hornet users and we can verify the claims made in the PR. We've not run into any issues.

We hope that the DCS – BIOS team will accept the PR and fix this for the hornet as well as look at the work done for other aircraft that use magnetically held switches where the approach would be appropriate

Sandra

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua [hunk 1]
```diff
@@ -873,7 +1093,7 @@ FA_18C_hornet:definePotentiometer("DEFOG_HANDLE", 11, 3005, 451, { -1, 1 }, "Def
 FA_18C_hornet:define3PosTumb("WSHIELD_ANTI_ICE_SW", 11, 3009, 452, "Defog Panel", "Windshield Anti-Ice/Rain Switch", { positions = { "ANTI ICE", "OFF", "RAIN" } })
 
 -- 12. Internal Canopy Switch
-FA_18C_hornet:defineRockerSwitch("CANOPY_SW", 7, 3001, 3001, 3002, 3002, 453, "Internal Canopy Switch", "Canopy Control Switch", { positions = { "OPEN", "HOLD", "CLOSE" } })
+FA_18C_hornet:defineElectricallyHeld3PosTumb("CANOPY_SW", 7, 3001, 3002, 453, "Internal Canopy Switch", "Canopy Control Switch", { magnetic_direction = "pos", positions = { "OPEN", "HOLD", "CLOSE" } })
```
Comment (charliefoxtwo) [inline Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: I'd prefer not to abuse attributes for this. I think there are two options:
1. add an extra parameter for this control definition, since this is the only thing that needs it
2. add full support for magnetically-held position documentation to attributes

I'd propose opting for the former in this PR - it will be simpler, and we can always go back and add full documentation later. Even if we did opt to add full support to attributes, attributes is really just for _documentation_ - not necessarily functional behavior. Functional behavior should drive attributes, not the other way around.

You might consider making this a table or something of like "positions which are magnetically held" (so `pos` would be `{ 1 }`, `neg` would be `{ -1 }`, and something like `both` would be `{ -1, 1 }`)

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua [hunk 2]
```diff
@@ -113,6 +113,226 @@ function FA_18C_hornet:defineMissionComputerSwitch(identifier, device_id, mc1_of
...
+				if dev then
+					dev:performClickableAction(command, 0)
+				end
+			end
+		end
+	end)
+
+	-- Control definition: same ControlType and inputs as predecessor
+	local control = Control:new(category, ControlType.action, identifier, description, {
+		SetStateInput:new(1, "set the switch position -- 0 = off, 1 = on"),
```
Comment (charliefoxtwo) [inline Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua:171]: Below in the input processor you support `TOGGLE` and `INC/DEC` (great), but here only a `SetStateInput` is defined. I'd recommend also adding `ActionInput` and `FixedStepInput` so that there are more input options available. This way, we'll be adding new input options to the majority of controls, and avoiding losing input options for `LTD_R_SW`

I've included a suggestion, but you'll likely need to add the imports

```suggestion
		FixedStepInput:new("switch to previous or next state"),
		SetStateInput:new(1, "set the switch position -- 0 = off, 1 = on"),
		ActionInput:new(ActionArgument.toggle, "toggle switch state"),
```

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua [hunk 3]
```diff
@@ -113,6 +113,226 @@ function FA_18C_hornet:defineMissionComputerSwitch(identifier, device_id, mc1_of
...
+--- @param device_id integer the dcs device id
+--- @param command integer the dcs command
+--- @param arg_number integer the dcs argument number
+--- @param category string the category in which the control should appear
+--- @param description string additional information about the control
+--- @param attributes SwitchAttributes? additional control attributes
+--- @return Control control the control which was added to the module
+function FA_18C_hornet:defineElectricallyHeldSwitch(identifier, device_id, command, arg_number, category, description, attributes)
+	-- Deferred release: 3 frames at 30Hz = ~100ms between press and release
+	local release_delay = 3
```
Comment (charliefoxtwo) [inline Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: I'd recommend making this all caps to indicate a constant. Also, as it's used in both functions, It might be better suited placed outside the scope of these functions, so we can tweak it in one place if needed.
```suggestion
	local RELEASE_DELAY = 3
```

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua [hunk 4]
```diff
@@ -113,6 +113,226 @@ function FA_18C_hornet:defineMissionComputerSwitch(identifier, device_id, mc1_of
...
+			release_countdown = release_countdown - 1
+			if release_countdown == 0 then
+				-- Countdown expired: send release (value 0) to DCS.
+				-- If DCS already auto-released (e.g. APU shutdown), harmless no-op.
+				local dev = GetDevice(device_id)
+				if dev then
+					dev:performClickableAction(command, 0)
+				end
+			end
+		end
```
Comment (charliefoxtwo) [inline Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: If `release_countdown` is 0, this will first export that the value of the switch is 1, and then it will set the switch to be released - and the export won't be updated until the following frame.

In practice this is probably fine, since the arg value will probably still be 1 after the release, however it might make more sense to put the `alloc:setValue` line after the `release_countdown` check, just in case?

**Review by charliefoxtwo — CHANGES_REQUESTED** [review]
Thank you for putting this together! Overall this looks great. I'm also checking with a couple of panel builders to make sure changes to existing switch behavior won't interfere with their panels.

The biggest thing blocking merging would be making sure we don't lose the action input (which is currently present on all the switches which use `defineToggleSwitchToggleOnly`) as well as the fixed step input which is present on the LTD/R switch.

Additionally, we should avoid stuffing properties into the attributes table - it would be better for the command to take a separate parameter for additional information like this, especially when it's critical to control behavior. The attributes table is really just for generated documentation at the moment.

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua (hunk 1 above)
Comment (BojoteX) [reply Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: Done. Moved to a dedicated `magnetic_positions` table parameter -- e.g. `{1}` for pos-only (Canopy), `{-1, 1}` for both (Engine Crank). Attributes now only carries documentation.

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua [hunk 5]
```diff
@@ -113,6 +113,227 @@ function FA_18C_hornet:defineMissionComputerSwitch(identifier, device_id, mc1_of
...
+--- matching the predecessor defineRockerSwitch. No new imports required.
+---
+--- @param identifier string the unique identifier for the control
+--- @param device_id integer the dcs device id
+--- @param pos_command integer the dcs command for the positive/right direction
+--- @param neg_command integer the dcs command for the negative/left direction
+--- @param arg_number integer the dcs argument number
+--- @param category string the category in which the control should appear
+--- @param description string additional information about the control
+--- @param magnetic_positions table positions which are magnetically held (e.g. {1}, {-1}, {-1, 1})
```
Comment (charliefoxtwo) [inline Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: always better to be more specific in the definition :)
```suggestion
--- @param magnetic_positions integer[] positions which are magnetically held (e.g. {1}, {-1}, {-1, 1})
```

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua (hunk 2 above)
Comment (BojoteX) [reply Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua:171]: Done. Added `FixedStepInput` and `ActionInput(toggle)` to the 2-pos control definition, plus the required imports. The input processor already handled these -- now the metadata matches.

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua (hunk 3 above)
Comment (BojoteX) [reply Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: Done. Moved to `local RELEASE_DELAY = 3` at module scope, shared by both functions.

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua (hunk 4 above)
Comment (BojoteX) [reply Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: Good catch. Reordered in both functions -- release fires first, then arg is read and exported.

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua (hunk 5 above)
Comment (BojoteX) [reply Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua]: Done.

**Comment by BojoteX** [comment]
All review comments addressed. Running through the full test plan now (all 8 switches, BORT, and hardware panels) before requesting re-review.

**Review by charliefoxtwo — APPROVED** [review]
I'm going to wait to hear back from panel makers before merging these changes, since they affect existing controls.

Thanks for putting this together. Should be a great improvement!

**Comment by BojoteX** [comment]
> I'm going to wait to hear back from panel makers before merging these changes, since they affect existing controls.
> 
> Thanks for putting this together. Should be a great improvement!

I'll also ask the OH folks to help test! they were happy with the changes, but I'll make sure they test the latest! thanks Charlie a pleasure dealing with you!

**Comment by BojoteX** [comment]
> I'm going to wait to hear back from panel makers before merging these changes, since they affect existing controls.
> 
> Thanks for putting this together. Should be a great improvement!

All tests went fine! lets hear back from the OH guys and other cockpit builders to make sure all is 100%..

**Comment by ashchan** [comment]
I've testes these OH switches again:

* Test APU
* APU Crank
* Fuel Dump
* Launch Bar
* Hook Bypass

They seem to go fine.

**Comment by eHanseJoerg** [comment]
I have tested the PR with the APU panel and can confirm it works very well, removing the need to implement sophisticated custom logic. 
My test setup is with FlitePal mag switches, connected to an Arduino Pro Micro connected to PC via USB.
Will test the same with RS485 connection tomorrow.

**Comment by charliefoxtwo** [comment]
panel builders I have reached out to have not reported any issues 🚀
